create table media_asset (
    id bigint generated by default as identity primary key,
    asset_id varchar(64) not null unique,
    original_filename varchar(255) not null,
    content_type varchar(100) not null,
    file_size bigint not null,
    sha256 varchar(64) not null unique,
    width integer not null,
    height integer not null,
    storage_path varchar(1024) not null,
    thumbnail_path varchar(1024),
    created_at timestamp with time zone not null
);

create table detection_task (
    id bigint generated by default as identity primary key,
    task_id varchar(64) not null unique,
    asset_id varchar(64) not null,
    status varchar(32) not null,
    failure_reason varchar(2048),
    created_at timestamp with time zone not null,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    constraint fk_detection_task_asset foreign key (asset_id) references media_asset(asset_id)
);

create index idx_detection_task_status_created_at on detection_task(status, created_at);

create table model_registry (
    id bigint generated by default as identity primary key,
    model_id varchar(64) not null unique,
    display_name varchar(255) not null,
    model_type varchar(64) not null,
    version varchar(64) not null,
    endpoint_url varchar(1024) not null,
    enabled boolean not null,
    default_threshold double precision not null,
    weight double precision not null,
    description varchar(2048),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table model_prediction (
    id bigint generated by default as identity primary key,
    prediction_id varchar(64) not null unique,
    task_id varchar(64) not null,
    model_id varchar(64) not null,
    model_version varchar(64) not null,
    raw_score double precision not null,
    normalized_score double precision not null,
    label varchar(32) not null,
    threshold_value double precision not null,
    latency_ms integer not null,
    raw_response_json text not null,
    created_at timestamp with time zone not null,
    constraint fk_model_prediction_task foreign key (task_id) references detection_task(task_id),
    constraint fk_model_prediction_model foreign key (model_id) references model_registry(model_id)
);

create index idx_model_prediction_task_id on model_prediction(task_id);

create table detection_report (
    id bigint generated by default as identity primary key,
    report_id varchar(64) not null unique,
    task_id varchar(64) not null unique,
    verdict varchar(32) not null,
    confidence double precision not null,
    summary varchar(2048) not null,
    risk_level varchar(32) not null,
    report_json text not null,
    created_at timestamp with time zone not null,
    constraint fk_detection_report_task foreign key (task_id) references detection_task(task_id)
);
