create table job_outbox (
    id bigint generated by default as identity primary key,
    event_id varchar(64) not null unique,
    event_type varchar(64) not null,
    aggregate_type varchar(64) not null,
    aggregate_id varchar(64) not null,
    payload_json text not null,
    status varchar(32) not null,
    attempt_count integer not null default 0,
    available_at timestamp with time zone,
    last_error varchar(2048),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    published_at timestamp with time zone,
    lock_version bigint not null default 0,
    constraint uq_job_outbox_aggregate_event unique (event_type, aggregate_id)
);

create index idx_job_outbox_claim on job_outbox(status, available_at, created_at);
create index idx_job_outbox_stale on job_outbox(status, updated_at);
